### ISSUE TITLE
Request: make the introduction more clear

### ISSUE THREAD

**Issue by mathiasbynens** [samuelgoto/proposal-block-params#3]
As someone unfamiliar with this functionality, this sentence tripped me up:

> For example, ```a {}``` is isomorphic to ```a(function() {})``` or ```a(1) {b()}``` is equivalent to ```a(1, function() {b()})```.

The first example is easy to follow, but the second one really takes it to another level. Can this be elaborated upon a bit more in the introduction? Moving to code blocks vs. giving these code examples inline in a sentence would already help a great deal:

```
a {}
// → is equivalent to →
a(function() {})

a(1) { b() }
// → is equivalent to →
a(1, function() { b() })
```

**Comment by samuelgoto** [comment]
done, moved to code blocks and tried to explain a bit further.
