### ISSUE TITLE
`do` example

### ISSUE THREAD

**Issue by mathiasbynens** [samuelgoto/proposal-block-params#4]
I’m a little confused by https://github.com/samuelgoto/proposal-dsls#do con. Is this example valid?
 IIRC, `do` is a keyword, so it cannot be used as an identifier. [`do` expressions](https://github.com/tc39/proposal-do-expressions) have their own proposal.

**Comment by samuelgoto** [comment]
ah, good catch, do can't be used as an identifier. done, removed from the examples! good catch, thanks!
